# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWF5dXNoMDI=
  MYSQL_DATABASE: bXlzcWxkYg==
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: YWF5dXNoMDI=
