name: Exploring Variables and Secrets
on:
  push
jobs:
  docker:
    env:
      CONTAINER_REGISTRY: docker.io
      IMAGE_NAME: github-actions-nginx
    runs-on: self-hosted
    steps:
      - name: Docker Build
        run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: Docker Login
        run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Publish
        run: docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    env:
      CONTAINER_REGISTRY: docker.io
      DOCKER_USERNAME: siddharthi
      IMAGE_NAME: github-actions-nginx
    needs: docker
    runs-on: self-hosted
    steps:
      - name: Docker Run
        run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
