apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config-page
  labels:
    name: html-config-page
data:
  index.html: |
    <html>
      <head><title>Hello</title></head>
      <body><h1>Hello from NGINX Pod!</h1></body>
    </html>
