apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest   
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/nginx/html
    - name: secret-volume
      mountPath: /etc/secret
  volumes:
  - name: config-volume
    configMap:
      name: html-config-page
  - name: secret-volume
    secret:
      secretName: nginx-secret
