apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    name: nginx-service
spec:
  selector:
    name: nginx-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  type: NodePort
