apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: dotnet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: 536697246803.dkr.ecr.ap-south-1.amazonaws.com/new_dotnet_image:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: awsecr-cred-secret
