apiVersion: v1
kind: Namespace
metadata:
  name: dotnet-app
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dotnet-app-quota
  namespace: dotnet-app
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
  
